#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_MIDIGURDY_KEYS)		+= mgurdy-keys.o
obj-$(CONFIG_MIDIGURDY_GPIO_KEYS)		+= mgurdy-gpio-keys.o
